# Generated by Django 2.1.5 on 2019-02-23 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phno', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='dishes',
            name='ncname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nc'),
        ),
    ]
