# Generated by Django 2.1.5 on 2019-02-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dishes',
            old_name='ncname',
            new_name='nc',
        ),
        migrations.AddField(
            model_name='dishes',
            name='filters',
            field=models.CharField(default='None', max_length=50),
            preserve_default=False,
        ),
    ]
