# Generated by Django 2.1.5 on 2019-02-25 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='filter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.filter'),
        ),
    ]
