# Generated by Django 2.1.5 on 2019-02-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_dishes_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishes',
            name='filters',
        ),
    ]
