# Generated by Django 2.1.5 on 2019-03-03 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190303_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_on_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='nc_comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='nc',
            name='comments',
        ),
        migrations.AddField(
            model_name='nc_comments',
            name='nc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nc'),
        ),
        migrations.AddField(
            model_name='comment_on_comment',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nc_comments'),
        ),
    ]
