# Generated by Django 2.1.5 on 2019-03-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190308_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current_items',
            name='items',
        ),
        migrations.AddField(
            model_name='dishes',
            name='currently_present',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='current_items',
        ),
    ]
